import 'package:ebook/Model/book_model.dart';

var bookData = [
  BookModel(
    id:"1",
    title: "The Power of Now",
    description: "The book draws from a variety of spiritual traditions, and one reviewer described it as Buddhism mixed with mysticism and a few references to Jesus Christ, a sort of New Age re-working of Zen. It uses these traditions to describe a belief system based on living in the present moment. Its core message is that people's emotional problems are rooted in their identification with their minds. The author writes that an individual should be aware of their present moment instead of losing themselves in worry and anxiety about the past or future.",
    aboutAuthor: "",
    author: "Eckhart Tolle",
    cover: "assets/images/book1.jpg",
    rating: "4.2",
    category: "Documentary",
    price: 100,
    pages: 100,
    language: "ENG",
    bookurl: "https://www.adphc.gov.ae/-/media/Project/ADPHC/ADPHC/Books-and-Publications/The-Power-of-now-Eng.pdf",
  ),
  BookModel(
      id:"2",
      title: "The Power of Positive Thinking",
      description: "is an incredibly impactful book that packs a wealth of wisdom into a concise format. Dr. Norman Vincent Peale's insights and principles are distilled into a short yet potent guide that has the potential to transform one's mindset and approach to life.",
      aboutAuthor: "",
      author: "Norman Vincent",
      cover: "assets/images/book2.jpg",
      rating: "4.5",
      category: "Documentary",
      price: 200,
    pages: 700,
    language: "ENG",
    bookurl: "https://www.law-of-attraction-haven.com/support-files/the-power-of-positive-thinking.pdf"
  ),
  BookModel(
      id:"3",
      title: "The 7 Habits of Highly Effective People",
      description: "In The 7 Habits of Highly Effective People, author Stephen R. Covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems. With penetrating insights and pointed anecdotes, Covey reveals a step-by-step pathway for living with fairness, integrity, service, and human dignity--principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.",
    aboutAuthor: "",
      author: "Stephen R.Covey",
      cover: "assets/images/book3.jpg",
      rating: "4.6",
      category: "Documentary",
      price: 100,
    pages: 172,
    language: "ENG",
    bookurl: "https://ati.dae.gov.in/ati12052021_1.pdf",
  ),
  BookModel(
      id:"4",
      title: "Read People like a Book",
      description: "Speed read people, decipher body language, detect lies, and understand human nature.Is it possible to analyze people without them saying a word? Yes, it is. Learn how to become a mind reader and forge deep connections.How to get inside people’s heads without them knowing.Read People Like a Book isn’t a normal book on body language of facial expressions. Yes, it includes all of those things, as well as new techniques on how to truly detect lies in your everyday life, but this book is more about understanding human psychology and nature. We are who we are because of our experiences and pasts, and this guides our habits and behaviors more than anything else. Parts of this book read like the most interesting and applicable psychology textbook you’ve ever read. Take a look inside yourself and others!",
      aboutAuthor: "",
      author: "Patrik King",
      cover: "assets/images/book9.jpg",
      rating: "4.4",
      category: "Documentary",
      price: 100,
    pages: 135,
    language: "ENG",
    bookurl: "https://eldritchdata.neocities.org/PDF/SE/HowToReadAPersonLikeABook%20.pdf"
  ),
];